/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./src/components/AuthAll/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./src/components/FixedActionBar/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./src/components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    NotAllowed: typeof import('./src/components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    PageMain: typeof import('./src/components/PageMain/index.vue')['default']
    PcasCascader: typeof import('./src/components/PcasCascader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./src/components/SystemInfo/index.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}
